Repository LLNL/thicket, pull requests merged in 2023-06, with the labels that each got.

#25 Update filter_metadata() test case for two columns
  thicket/tests/test_columnar_join.py
  thicket/tests/test_filter_metadata.py
Labels: status-ready-for-review

#28 Updated visualization functions
  thicket/stats/display_boxplot.py
  thicket/stats/display_heatmap.py
  thicket/stats/display_histogram.py
Labels: status-ready-for-review

#26 Updates the profile information of created Sub-Thickets
  thicket/tests/test_groupby.py
  thicket/thicket.py
Labels: status-ready-for-review

#37 Update to allow get_perf_columns to work with columnar joined thicket
  thicket/helpers.py
  thicket/thicket.py
Labels: status-ready-for-review

#36 Boxplot Index Update
  thicket/stats/calc_boxplot_statistics.py
Labels: status-ready-for-review

#35 Update to get_unique_metadata for columnar join
  thicket/thicket.py
Labels: status-ready-for-review

#24 Correct old references that don't match to current
  thicket/__init__.py
  thicket/helpers.py
  thicket/model_extrap.py
  thicket/tests/test_filter_metadata.py
  thicket/tests/test_filter_stats.py
  thicket/tests/test_groupby.py
  thicket/tests/test_make_superthicket.py
  thicket/tests/test_thicket.py
  thicket/thicket.py
Labels: area-docs, priority-normal, status-work-in-progress, type-internal-cleanup

#39 update for v2023.2.0a0
  pyproject.toml
  thicket/version.py
Labels: priority-normal, status-ready-to-merge, type-release

#40 bump for v2023.2.0
  pyproject.toml
  thicket/version.py
Labels: priority-normal, status-ready-to-merge, type-release

#45 Updates dependencies in setup.py and requirements.txt
  build_requirements.sh
  requirements.txt
  setup.py
Labels: area-deployment, priority-normal, status-ready-for-review, type-bug

#42 Adds usability of show_metric_columns() to statistic functions
  thicket/stats/calc_boxplot_statistics.py
  thicket/stats/check_normality.py
  thicket/stats/correlation_nodewise.py
  thicket/stats/maximum.py
  thicket/stats/mean.py
  thicket/stats/median.py
  thicket/stats/minimum.py
  thicket/stats/percentiles.py
  thicket/stats/std.py
  thicket/stats/variance.py
Labels: area-stats, priority-normal, status-ready-for-review

#47 update version in conf.py
  docs/conf.py
Labels: area-docs, priority-normal, status-ready-to-merge

#46 add thicket documentation and tutorial through read the docs
  .readthedocs.yml
  docs/_static/custom.css
  docs/conf.py
  docs/developer_guide.rst
  docs/environment.yml
  docs/generating_data.rst
  docs/getting_started.rst
  docs/images/Table-Tree-Revised-gradien.png
  docs/images/appended_statsdf.png
  docs/images/empty_statsdf.png
  docs/images/ensembleframe.png
  docs/images/metadataframe.png
  docs/images/ql-original.png
  docs/images/thicket_tutorial_34_1.png
  docs/images/thicket_tutorial_36_1.png
  docs/images/thicket_tutorial_37_1.png
  docs/index.rst
  docs/requirements.txt
  docs/source/modules.rst
  docs/source/thicket.rst
  docs/source/thicket.stats.rst
  docs/source/thicket.vis.rst
  docs/test.md
  docs/thicket_structures.rst
  docs/thicket_tutorial.ipynb
Labels: status-ready-for-review

#49 bump for hotfix release 2023.2.1
  docs/conf.py
  pyproject.toml
  thicket/version.py
Labels: priority-high, status-ready-to-merge, type-release
