Repository LLNL/thicket, pull requests merged in 2025-07, with the labels that each got.

#236 Unit Test for node_ordering Setting
  thicket/tests/conftest.py
  thicket/tests/data/caliper-ordered/230525-151052_1930517_eWbGeyrlBOPT_copy.cali
  thicket/tests/test_caliperreader.py
Labels: area-tests, priority-normal, status-ready-for-review, type-bug

#240 Enable timemory Reader
  thicket/thicket.py
Labels: status-ready-for-review

#223 Re-exports QueryMatcher from __init__.py to be consistant with Hatchet
  thicket/__init__.py
Labels: area-query-lang, priority-normal, status-ready-for-review, type-feature

#225 Unicode Histogram in Tree
  thicket/external/console.py
  thicket/thicket.py
Labels: area-visualization, priority-normal, status-ready-for-review, type-feature

#249 Enable numpy >= 2.0
  requirements.txt
  setup.py
Labels: area-external, status-ready-for-review

#255 display more than 2 metrics on the tree visualization
  thicket/external/console.py
  thicket/tests/test_tree.py
Labels: status-ready-for-review
